### ISSUE TITLE
Changes to the open source code

### ISSUE THREAD

**Issue by Connor200024** [dmod-gg/dmod#4] opened 2021-05-07 21:26 UTC
Hi,

I have a few things i wish to point out as i see this is open source now....

Frist off you are exposing Window's Database. (This is in the .env)

Another thing, you are exposing your token.... (Ish stupid ngl, come on devs should know this stuff)

Please fix this, i am only saying this because some one someone is gonna attempt something stupid... Welcome to the internet! 😊

Thanks,

Connor200024

**Comment by MaximKing1** [comment] 2021-05-07 21:27
https://github.com/dmod-gg/dmod/pull/3
Fixed the changes here

**Comment by MattA-Official** [comment] 2021-05-08 08:20
duplicate of #5 (exposure of environmental files)

**Closed by MattA-Official** 2021-05-08 08:20 UTC

**Comment by MattA-Official** [comment] 2021-05-08 10:10
duplicate of #5
