### ISSUE TITLE
Bug Report: Changes detected on Settings page in weird location

### ISSUE THREAD

**Issue by srnyx** [dmod-gg/dmod#34] opened 2021-08-11 19:12 UTC
Reproduce: Sign in --> Settings --> Change something

![image](https://user-images.githubusercontent.com/25808801/129089065-b9d34a9e-4f10-425b-a2a1-4ddbbbe1d376.png)

**Comment by MattA-Official** [comment] 2021-08-11 19:45
duplicate of #33

**Closed by MattA-Official** 2021-08-11 19:45 UTC
Labels: bug
