### ISSUE TITLE
Browser can’t establish a connection to the websocket

### ISSUE THREAD

**Issue by 3o8** [dmod-gg/dmod#38] opened 2021-08-11 19:22 UTC
Bug: Every now and then an error appears on the console saying: Firefox can’t establish a connection to the server at wss://gateway.dmod.gg/ this makes the the "Connecting to Gateway" be on the website 24/7

How to reproduce: Just hop on the site.

Attachments:
![image](https://user-images.githubusercontent.com/68564141/129090215-2a530951-ca0f-4d17-8c32-2f63ad3f4a09.png)

**Comment by MattA-Official** [comment] 2021-08-11 19:48
duplicate of #21

**Closed by MattA-Official** 2021-08-11 19:48 UTC
