### ISSUE TITLE
Bug Report: Profile won't load

### ISSUE THREAD

**Issue by vagabondlol** [dmod-gg/dmod#43] opened 2021-08-12 07:00 UTC
Bug: When you load up the site, sometimes the profile icon will constantly load.

How to reproduce: Load up the site (you don't need to be signed-out) and see if it happens. the profile pic will be grey with the loading animation. 

Screenshot/Recording:

https://user-images.githubusercontent.com/48355895/129152016-b88f9cbf-6532-4c50-8a0c-cbe71f4b4a49.mov

**Comment by Wilbert-mad** [comment] 2021-08-12 16:03
![](https://user-images.githubusercontent.com/63362762/129229114-b640fc86-4f36-42ee-8864-eb23d082b5d1.png)
We're having trouble with both `current_user` and `search_g` routes. User route is returning this, and search route is returning an internal server error. It's a server error, as the local version works fine. At least from my testing.

**Comment by vagabondlol** [comment] 2021-08-13 13:23
> ![](https://user-images.githubusercontent.com/63362762/129229114-b640fc86-4f36-42ee-8864-eb23d082b5d1.png)
> We're having trouble with both `current_user` and `search_g` routes. User route is returning this, and search route is returning an internal server error. It's a server error, as the local version works fine. At least from my testing.

how do we fix it? I've seen multiple people talk about this issue

**Comment by MattA-Official** [comment] 2021-08-16 18:33
The root cause will be investigated shortly.

**Comment by MattA-Official** [comment] 2021-08-16 19:59
Should be fixed in e5ef0404632ab7083ecbc02438764b2a7acade55

**Closed by MattA-Official** 2021-08-16 19:59 UTC
Labels: bug
